name: CI/CD on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo systemctl start docker
        docker --version

    - name: Build Docker Image
      run: |
        docker build -t backend_taitra:latest .

  test:
    runs-on: self-hosted
    needs: build

    steps:
    - name: Run Docker Container
      run: |
        docker run --rm -d -e SECRET_KEY="${{ secrets.SECRET_KEY}}" -e DB_URL="${{secrets.DB_URL_TEST}}" -e DB_USERNAME="${{ secrets.DB_USERNAME}}" -e DB_PASSWORD="${{ secrets.DB_PASSWORD_TEST}}" -p 9091:9090 --name taitra_container backend_taitra:latest

    
    - name: Wait for Service to Start
      run: sleep 10

    - name: Test API Heartbeat
      run: |
        curl --request GET \
        --url http://localhost:9091/api/v1/heartbeat \
        --header 'User-Agent: insomnia/8.4.5'

    - name: Stop Docker Container
      run: |
        docker stop taitra_container

    - name: Notify Success
      run: echo "Build, deployment, and testing completed successfully!"

  ECR:
    runs-on: self-hosted
    needs: test

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Tag Docker image
      run: |
        docker tag backend_taitra:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend_taitra:latest

    - name: Push to Amazon ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend_taitra:latest
    - name: Notify Success
      run: echo "Docker image successfully pushed to ECR!"
